---
- name: Create PKP config file from the site's diccionary vars.
  hosts: all
  become: yes
  gather_facts: no
  vars:
    siteParam: "{{ site }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./sites/{{ site }}.yml
  tasks:
    - name: Ensure journal's directory exists
      file:
        path: "{{ path.files.config }}/{{ dojo.id }}"
        state: directory
        force: yes

    - name: Convert versionFamily to major_minor format
      set_fact:
        versionMajorMinor: "{{ dojo.versionFamily.split('_')[0] }}_{{ dojo.versionFamily.split('_')[1] }}"

    - name: Generate apache-config file from template and dojo vars.
      template:
        src: "./templates/{{ dojo.tool }}/apache.ojs.conf-{{ versionMajorMinor }}-{{ dojo.type }}.j2"
        dest: "{{ path.files.config }}/{{ dojo.id }}/apache.conf"

