---
- name: Create an APACHE virtual host file from the site's diccionary vars.
  hosts: all
  become: yes
  gather_facts: no
  vars:
    siteParam: "{{ site }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./sites/{{ siteParam }}.yml
  tasks:
    - name: Load vars from dojo.yml
      include_vars:
        file: ./configs/dojo.yml
        name: dojoVars

    - name: Load vars from site.yml
      include_vars:
        file: ./sites/{{ siteParam }}.yml
        name: siteGenericVars
      ignore_errors: yes

    - name: If exists, load vars from site-host.yml
      include_vars:
        file: ./sites/{{ siteParam }}-{{ ansible_hostname }}.yml
        name: siteHostVars
      ignore_errors: yes
      failed_when: false

    - name: Combine siteGenericVars and siteHostVars
      set_fact:
        allVars: "{{ dojoVars | combine(siteGenericVars | default({}), recursive=True) | combine(siteHostVars | default({}), recursive=True) }}"

    - name: Ensure site directory exists
      file:
        path: "{{ allVars.path.base.sites }}/{{ allVars.dojo.id }}"
        state: directory
        force: yes

    - name: Convert versionFamily to major_minor format
      set_fact:
        versionMajorMinor: "{{ allVars.dojo.versionFamily.split('_')[0] }}_{{ allVars.dojo.versionFamily.split('_')[1] }}"

    - name: Generate apache-config file from template and dojo vars
      template:
        src: "./templates/{{ allVars.dojo.tool }}/apache.ojs.conf-{{ versionMajorMinor }}-{{ allVars.dojo.type }}.j2"
        dest: "{{ allVars.path.files.config }}/{{ allVars.dojo.id }}/apache.conf"

