---
- name: Create PKP's config file from the site's diccionary vars.
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    siteParam: "{{ site }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
    hostname: "{{ ansible_hostname }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./sites/base-{{ ansible_hostname }}.yml
  tasks:
    # sets "allVars" array from the site's diccionaries as follows:
    #           baseHost > siteGeneric > siteHost > dojoVars.
    - include: setAllVars.yml
  
    # - name: DEBUG - Shows the result of the combination
    #   debug:
    #     msg: "{{ allVars }}"

    - name: Ensure site directory exists
      file:
        path: "{{ allVars.path.files.config }}/{{ allVars.dojo.id }}"
        state: directory
        force: yes

    - name: Generate config file from template and dojo vars.
      template:
        src: "./templates/{{ allVars.dojo.tool }}/config.inc.php-{{ allVars.dojo.versionFamily }}.j2"
        dest: "{{ allVars.path.files.config }}/{{ allVars.dojo.id }}/config.inc.php"