---
- name: Create PKP config file from the site's diccionary vars.
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    siteParam: "{{ site }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./sites/{{ site }}.yml
  tasks:
    - name: Ensure journal's directory exists
      file:
        path: "{{ path.files.config }}/{{ dojo.id }}"
        state: directory
        force: yes

    - name: Generate config file from template and dojo vars.
      template:
        src: "./templates/{{ dojo.tool }}/config.inc.php-{{ dojo.versionFamily }}.j2"
        dest: "{{ path.files.config }}/{{ dojo.id }}/config.inc.php"
