---
- name: Create PKP's config file from the site's diccionary vars.
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    hostName: "{{ host }}"
    siteParam: "{{ site }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./sites/base-{{ hostName }}.yml
  tasks:
    # sets "allVars" array from the site's diccionaries as follows:
    #           baseHost > siteGeneric > siteHost > dojoVars.
    - include_tasks: setAllVars.yml
  
    - name: Generate config file from template and dojo vars.
      template:
        src: "./templates/{{ allVars.dojo.tool }}/config.inc.php-{{ allVars.dojo.versionFamily }}.j2"
        dest: "{{ allVars.path.files.config }}/{{ allVars.dojo.id }}/config.inc.php"