---
- name: Create PKP docker-compose files from the site's diccionary vars.
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    siteParam: "{{ site }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./sites/{{ site }}.yml
  tasks:
    - name: Load vars from dojo.yml
      include_vars:
        file: ./configs/dojo.yml
        name: dojoVars

    - name: Load vars from site.yml
      include_vars:
        file: ./site/{{ site }}.yml
        name: siteGenericVars

    - name: If exists, load vars from site-host.yml
      include_vars:
        file: ./site/{{ site }}-{{ ansible_hostname }}.yml
        name: siteHostVars
      ignore_errors: yes
      
    - name: Combine siteGenericVars and siteHostVars
      set_fact:
        allVars: "{{ dojoVars | combine(siteGenericVars, recursive=True) | combine(siteHostVars, recursive=True) | default({}) }}"

    - name: Ensure site directory exists
      file:
        path: "{{ path.base.site }}/{{ allVars.dojo.id }}"
        state: directory
        force: yes

    - name: Convert versionFamily to major_minor format
      set_fact:
        versionMajorMinor: "{{ allVars.dojo.versionFamily.split('_')[0] }}_{{ allVars.dojo.versionFamily.split('_')[1] }}"
          
    - name: Generate docker-compose.yml file from template and dojo vars.
      template:
        src: "./templates/{{ allVars.dojo.tool }}/docker-compose.yml-{{ versionMajorMinor }}.j2"
        dest: "{{ path.base.sites }}/{{ allVars.dojo.id }}/docker-compose.yml"

    - name: Generate docker-compose.override.yml file from template and dojo vars.
      template:
        src: "./templates/{{ dojo.tool }}/docker-compose.override.yml-{{ versionMajorMinor }}.j2"
        dest: "{{ path.base.sites }}/{{ allVars.dojo.id }}/docker-compose.override.yml"