# Justfile for dojo actions

# Default values
vaultPath := './configs/secret.yml'
vaultKey  := './configs/.vault.key'
dojoPath  := '/home/marc/workspace/dojo/playbooks/dojo'

# Shows how to use the script.
dojo-help:
    @cat {{dojoPath}}/README.md

    # Full list of infrastructure playbooks is:
    @tree --noreport {{dojoPath}}/run
    @tree --noreport {{dojoPath}}/info

# Syntax and examples
dojo-info:
    # README DOJO
    # To get a list of actions use "just dojo"
    @# TBD
    #

# Creates an ansible vault with default. Actions are:
# - create: Vault is saved at "configs/secrets.yml" with the password passed and stored at .vault.key (check your permissions).
# - edit:   Edits the deault vault in "configs/secrets.yml" with the password stored at .vault.key:
dojo-vault action:
    @if [[ "${action}" == "create" ]]; then \
        echo "${2}" >> ${vaultKey}; \
        ansible-vault create --vault-password-file=${vaultKey} ${vaultPath} \
    elif [[ "${create}" == "edit" ]]; then \
        ansible-vault edit --vault-password-file={{vaultKey}} {{vaultPath}} \
    else \
        echo "Unknown action"; \
    fi

# Create a config.inc.php based on the specified dictionary name (ie: periodicum). Vault need to be created first.
# Crea un fichero en "/tmp/>name>.config.inc.php" con la plantilla de /templates/<site>.yml y las variables del diccionario "/sites/<name>.yml"
dojo-site-old action name:
    #!/bin/bash
    echo "{{action}} - {{name}}"
    case ${action} in \
        create-config) \
            ansible-playbook -i host, --vault-password-file {{vaultKey}} ./pkp-config.yml -e "site={{ name }}" \
        ;; \
        create-all) \
            echo "Create ALL: {{action}} - {{name}}" \
        ;; \
    esac

# Create a full site or specific files based on the specified dictionary name (ie: periodicum). Vault need to be created first.
# config: Creates "/tmp/>name>.config.inc.php" with the template /templates/<site>.yml and the vars from "/sites/<name>.yml"
dojo-play action site host:
    ansible-playbook -i host, --vault-password-file {{ vaultKey }} {{ dojoPath }}/run/pkp-{{ action }}.yml -e "site={{ site }}" \
