- name: Set permissions in journal's folders structure
  hosts: all
  become: true
  gather_facts: yes
  vars:
    hostName: "{{ host }}"
    siteParam: "{{ site }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./inventory/sites/base-{{ hostName }}.yml
  tasks:
    - include_tasks: ../setAllVars.yml
      vars:
        mode: site
        param: "{{ siteParam }}"
  
    - name: Assign user and group for BD folders
      file:
        path: "{{ item }}"
        state: directory
        mode: "{{ allVars.volumes.db.mode }}"
        owner: "{{ allVars.volumes.db.owner }}"
        group: "{{ allVars.volumes.db.group }}"
        recurse: yes
      loop:
        - "{{ allVars.path.volumes.db }}/{{ allVars.dojo.id | lower}}"
      tags:
        - volumes_db

    - name: Assign user and group for WWW folders
      file:
        path: "{{ item }}"
        state: directory
        mode: "{{ allVars.volumes.app.mode }}"
        owner: "{{ allVars.volumes.app.owner }}"
        group: "{{ allVars.volumes.app.group }}"
        recurse: yes
      loop:
        - "{{ allVars.path.files.config }}/{{ allVars.dojo.id | lower }}"
        - "{{ allVars.path.files.public }}/{{ allVars.dojo.id | lower }}"
        - "{{ allVars.path.files.private }}/{{ allVars.dojo.id | lower }}"
        - "{{ allVars.path.volumes.logs }}/{{ allVars.dojo.id | lower }}/app"
      tags:
        - volumes_www
