---
- name: Syncs from remote host and upgrades to last LTS version.
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    hostName: "{{ host }}"
    siteParam: "{{ site }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./sites/base-{{ hostName }}.yml
  tasks:
    # sets "allVars" array from the site's diccionaries as follows:
    #           baseHost > siteGeneric > siteHost > dojoVars.
    - include: setAllVars.yml
  
    - name: Check if the site directory exists
      stat:
        path: "{{ allVars.path.base.sites }}/{{ allVars.dojo.id }}"
      register: site_dir_stat

    - name: Fail if site directory does not exist
      fail:
        msg: "Site directory does not exist: run dojo-create first."
      when: not site_dir_stat.stat.exists

    - name: Syncs remote folders (public and private) and last DB dump. 
      command: "/home/marc/serverMigration/getRemoteVol.sh {{ allVars.dojo.id }}"

    - name: List contents of /srv/volumes/db/{{ allVars.dojo.id }} before deletion
      shell: ls -l "{{ allVars.path.base.sites }}/{{ allVars.dojo.id }}/volumes/db/"
      register: before_deletion_output
      ignore_errors: yes

    # - debug: DB folder of journal [{{ allVars.dojo.id }}]
    #     var: before_deletion_output.stdout_lines

    - name: Resets the site - Docker compose down.
      shell: |
        docker compose down;
      args:
        chdir: "{{ allVars.path.base.sites }}/{{ allVars.dojo.id }}"
      register: docker_compose_output

    - name: Raises the site - Docker compose up and wait for MySQL readiness
      shell: |
        docker compose up -d
        LOOP=0
        until docker compose logs | grep -q -e "\[Entrypoint\]: Stopping temporary server" -e "\[Entrypoint\]: MariaDB upgrade not required"; do
          if [ $LOOP -ge 30 ]; then
            echo "JOURNAL [{{ allVars.dojo.id }}]: Timeout of 1 minute reached, exiting."
            exit 1
          fi
          ((LOOP++))
          sleep 10
        done
        sleep 10
      args:
        chdir: "{{ allVars.path.base.sites }}/{{ allVars.dojo.id }}"
      register: docker_compose_output
      ignore_errors: yes

    - name: Check if the previous task failed
      fail:
        msg: "Timeout reached or an error occurred while waiting for MySQL readiness."
      when: docker_compose_output.rc != 0

    - name: Debug output if successful
      debug:
        msg: "MySQL readiness confirmed."
      when: docker_compose_output.rc == 0

    - name: Upgrades to OJS 3.3
      shell: |
        docker exec ojs_app_{{ allVars.dojo.id }} php tools/upgrade.php check 2>&1 | tee volumes/logs/upgrade3.log;
        docker exec ojs_app_{{ allVars.dojo.id }} php tools/upgrade.php upgrade 2>&1 | tee -a volumes/logs/upgrade3.log;
      args:
        chdir: "{{ allVars.path.base.sites }}/{{ allVars.dojo.id }}"
      register: docker_compose_output
