---
- name: Mostrar información de snapshots en el pool "srv/volumes"
  hosts: all
  gather_facts: False
  tasks:
    - name: Obtener lista de volúmenes en el pool "srv/volumes"
      command: "zfs list -H -t volume -o name -r srv/volumes"
      register: volumenes

    - name: Obtener información de snapshots para cada volumen
      shell: "zfs list -H -t snapshot -o name,creation -r {{ item }}"
      register: snapshots
      loop: "{{ volumenes.stdout_lines }}"

    - name: Imprimir información de snapshots
      debug:
        msg: |
          "Volumen: {{ item.0.split('/')[2] }}, Snapshots: {{ item.1.stdout_lines | length }}, Último Snap: {{ item.1.stdout_lines[-1].split('\t')[1] }}"
          {{ item }}
      loop: "{{ snapshots.results }}"
