# Versió: stable-3_3_0

dojo:
  id: fraseolex                     # This MUST be lowercase.
  domain: "ada-revistes.precarietat.net"
  type: folder-noslug               # How the url will be managed?
  version: "3_3_0-19"
  versionFamily: "3_3_0"

images:
  app: "pkpofficial/{{ dojo.tool }}:stable-3_3_0"

proxy:                              # Refered vars should be overridden.
  domains: "`ada-revistes.precarietat.net`,`revistes.uab.cat`,`revistes.uab.es`"
  pathprefix: "fraseolex"

pkp:
  general:
    installed: "On"
    base_url: "https://ada-revistes.precarietat.net/fraseolex"
    base_url_index: "https://ada-revistes.precarietat.net/fraseolex/index"
    base_url_journal: "https://ada-revistes.precarietat.net/fraseolex"
    scheduled_tasks: "On"
    restful_urls: "On"
    enable_beacon: "Off"
  email:
    smtp: "Off"
    smtp_auth: "tls"
    dmarc_compliant_from_displayname: "%n via Fraseolex (UAB)"
  oai:
    id: fraseolex.revistes.uab.cat