# Memory limit & execution time changes for the upgrade

dojo:
  id: isogloss                      # This MUST be lowercase.
  domain: "revistes.uab.cat"
  type: folder-noslug               # How the url will be managed?

proxy:                              # Refered vars should be overridden.
  domains: "`revistes.uab.cat`,`revistes.uab.es`"
  pathprefix: "isogloss"

php:
  memory_limit: 1024M
  max_execution_time: 600

pkp:
  general:
    installed: "On"
    base_url: "https://revistes.uab.cat/isogloss"
    base_url_index: "https://revistes.uab.cat/isogloss/index"
    base_url_journal: "https://revistes.uab.cat/isogloss"
    scheduled_tasks: "On"
    restful_urls: "On"
    enable_beacon: "On"
  email:
    smtp: "On"
    smtp_auth: "tls"
    dmarc_compliant_from_displayname: "%n via Isogloss (UAB)"
  oai:
    id: isogloss.revistes.uab.cat