# Versió: stable-3_3_0

dojo:
  id: jhsgl                         # This MUST be lowercase.
  domain: "revistes.uab.cat"
  type: folder-noslug               # How the url will be managed?
  version: "3_3_0-19"
  versionFamily: "3_3_0"

images:
  app: "pkpofficial/{{ dojo.tool }}:stable-3_3_0"

proxy:                              # Refered vars should be overridden.
  domains: "`revistes.uab.cat`,`revistes.uab.es`"
  pathprefix: "jhsgl"

pkp:
  general:
    installed: "On"
    base_url: "https://revistes.uab.cat/jhsgl"
    base_url_index: "https://revistes.uab.cat/jhsgl/index"
    base_url_journal: "https://revistes.uab.cat/jhsgl"
    scheduled_tasks: "On"
    restful_urls: "On"
    enable_beacon: "On"
  email:
    smtp: "On"
    smtp_auth: "tls"
    dmarc_compliant_from_displayname: "%n via Journal Human Security (UAB)"
  oai:
    id: jhsgl.revistes.uab.cat