dojo:
  id: locus                         # This MUST be lowercase.
  domain: "revistes.uab.cat"
  type: folder-noslug               # How the url will be managed?

proxy:                              # Refered vars should be overridden.
  domains: "`revistes.uab.cat`,`revistes.uab.es`"
  pathprefix: "locus"

php:
  memory_limit: 256M
  post_max_size: 40M
  upload_max_filesize: 40M

pkp:
  general:
    installed: "On"
    base_url: "https://revistes.uab.cat/locus"
    base_url_index: "https://revistes.uab.cat/locus/index"
    base_url_journal: "https://revistes.uab.cat/locus"
    scheduled_tasks: "On"
    restful_urls: "On"
    enable_beacon: "On"
  email:
    smtp: "On"
    smtp_auth: "tls"
    dmarc_compliant_from_displayname: "%n via Locus Amoenus (UAB)"
  oai:
    id: locus.revistes.uab.cat