## Proves a ADA

dojo:
  id: periodicum                    # This MUST be lowercase.
  domain: "ada-revistes.precarietat.net"
  type: folder-noslug               # How the url will be managed?

proxy:                              # Refered vars should be overridden.
  domains: "`ada-revistes.precarietat.net`,`revistes.uab.cat`,`revistes.uab.es`"
  pathprefix: "periodicum"

pkp:
  general:
    installed: "On"
    base_url: "https://ada-revistes.precarietat.net/periodicum"
    base_url_index: "https://ada-revistes.precarietat.net/periodicum/index"
    base_url_journal: "https://ada-revistes.precarietat.net/periodicum"
    scheduled_tasks: "On"
    restful_urls: "On"
    enable_beacon: "Off"
  email:
    smtp: "On"
    smtp_auth: "tls"
    dmarc_compliant_from_displayname: "%n via Periodicum PROVES-ADA (UAB)"
  oai:
    id: periodicum.revistes.uab.cat