---
- name: Create a full folder for the service from the service's diccionary vars
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    siteParam: "{{ service }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./services/{{ service }}.yml
  tasks:
    - name: Ensure traefik's directory exists
      file:
        path: "{{ path.base.service }}/{{ dojo.id }}"
        state: directory
        force: yes

    - name: Generate docker-compose file from template and dojo vars
      template:
        src: "./templates/services/docker-compose-{{ dojo.tool }}.j2"
        dest: "{{ path.base.service }}/{{ dojo.id }}/docker-compose.yml"

    - name: Generate env file from template and dojo vars
      template:
        src: "./templates/services/env.j2"
        dest: "{{ path.base.service }}/{{ dojo.id }}/.env"

    - name: Ensure treafik's essential folders exists
      file:
        path: "{{ item }}"
        state: directory
        mode: 0744
        owner: "{{ user.run }}"
        group: "{{ user.group }}"
        force: yes
      loop:
        - "{{ path.base.service }}/{{ dojo.id }}"
        - "{{ path.storage.backups }}/{{ dojo.id }}"
        - "{{ path.storage.volumes }}/files"

    - name: Create journal's volume folders
      file:
        path: "{{ item.value }}/{{ dojo.id }}"
        state: directory
        mode: 0744
        owner: "{{ user.run }}"
        group: "{{ user.group }}"
        recurse: yes
      with_dict: "{{ path.volumes }}"
      tags:
        - volumes_directories

    - name: Create journal's volume folders for files
      file:
        path: "{{ item.value }}/{{ dojo.id }}"
        state: directory
        mode: 0744
        owner: "{{ user.run }}"
        group: "{{ user.group }}"
        recurse: yes
      with_dict: "{{ path.files }}"
      tags:
        - files_directories

    - name: Restric permissions to certificates and ACME files
      file:
        path: "{{ item }}"
        state: directory
        mode: 0600
        owner: "{{ user.run }}"
        group: "{{ user.group }}"
        force: yes
      loop:
        - "{{ path.storage.volumes }}/all/{{ dojo.id }}/certificates"

    - name: Create required symbolic links
      file:
        src: "{{ item.target }}"
        dest: "{{ item.link }}"
        state: link
      loop: 
        - { link: "{{ path.base.service }}/{{ dojo.id }}/volumes", target: "{{ path.volumes.all }}/{{ dojo.id }}" }
        - { link: "{{ path.volumes.all }}/{{ dojo.id }}/db", target: "{{ path.volumes.db }}/{{ dojo.id }}" }
        - { link: "{{ path.volumes.all }}/{{ dojo.id }}/logs", target: "{{ path.volumes.logs }}/{{ dojo.id }}" }
        - { link: "{{ path.volumes.all }}/{{ dojo.id }}/config", target: "{{ path.files.config }}/{{ dojo.id }}" }
        - { link: "{{ path.volumes.all }}/{{ dojo.id }}/public", target: "{{ path.files.public }}/{{ dojo.id }}" }
        - { link: "{{ path.volumes.all }}/{{ dojo.id }}/private", target: "{{ path.files.private }}/{{ dojo.id }}" }
