---
- name: Create PKP config file from the site's diccionary vars.
  hosts: all
  gather_facts: no
  vars:
    siteParam: "{{ site }}"
  vars_files:
    - ./sites/{{ site }}.yml
  tasks:    
    - name: Generate config file from template and dojo vars.
      template:
        src: "./templates/{{ dojo.tool }}/config.inc.php-{{ dojo.versionFamily }}.j2"
        dest: "/tmp/{{ dojo.id }}.config.inc.php"

