---
- name: Show docker and docker-compose versions (for outdated versions)
  hosts: all
  become: yes
  connection: ssh

  tasks:
    - name: Show versions
      shell: docker -v && docker-compose -v && cat /etc/issue
      register: output

    - name: Show the value of output
      debug: var=output.stdout_lines
