---
- name: Show docker and docker compose versions.
  hosts: all
  become: yes

  tasks:
    - name: Show versions
      #shell: docker -v && docker-compose -v && cat /etc/issue
      shell: docker -v && docker compose version && cat /etc/issue
      register: output

    - name: show the value of output
      debug: var=output.stdout_lines
