---
- name: Installs extra tools (not esential but helpfull).
  hosts: all
  become: yes 

  tasks:
    - name: Update the repository cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'  # Check if the system is debian based.

    - name: Installs tmux, vim, tree, htop and tldr.
      apt:
        name:
          - tmux
          - vim
          - tree
          - htop
          - tldr
        state: present
      when: ansible_os_family == 'Debian'

    # Configurar Vim
    - name: Copies the vim config file.
      copy:
        src: ./configs/vimrc
        dest: ~/.vimrc
      become: yes

    # Actualizar TLDR
    - name: Updates TLDR
      command: tldr --update
      when: ansible_os_family == 'Debian'  # Puedes ajustar esto según la distribución
