# Justfile for infra

# Variables
runPath := '/home/marc/workspace/dojo/playbooks/infra'

# This list of actions.
infra:
    just -l

# Shows how to use the script.
infra-help:
    @cat {{runPath}}/README.md

    # Full list of infrastructure playbooks is:
    @tree --noreport {{runPath}}/run
    @tree --noreport {{runPath}}/info

# Installs ansible and it's roles in your laptop.
infra-install-ansible:
    sudo python3 -m venv venv
    # Activa el entorno virtual (en sistemas Unix/Linux)
    bash -c "source venv/bin/activate"
    sudo apt install ansible git
    ansible-galaxy install -r requirements.yml
    ansible-galaxy collection install community.general
    # Keep changes under version control
    git init && git add . && git commit -m "Initial commit"

# Runs a playbook as root. Parameter includes the path (info/ or run/) and the playbook name.
infra-play playbook host:
    ansible-playbook -i {{host}}, ./playbooks/infra/{{playbook}}.yml -K

# Shows the description of the specified playbook
infra-show playbook:
    cat ./playbooks/infra/{{playbook}}.yml | grep name

# Runs a dist-upgrade, remove unused dependences and reboot.
infra-dist-upgrade host:
    ansible-playbook -i {{host}}, run/dist-upgrade.yml -K

# Runs an "apt update" and "apt ugrade" and show the result.
infra-update-upgrade host:
    ansible-playbook -i {{host}}, run/update-upgrade.yml -K
