---
- name: Creates a service running playbooks service-folders > env > docker-compose > permissions.
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    hostName: "{{ host }}"
    serviceParam: "{{ service }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./inventory/services/base-{{ hostName }}.yml
  tasks:
    - include_tasks: ../setAllVars.yml
      vars:
        mode: service
        param: "{{ serviceParam }}"

    - name: Ensure proxy network exists
      community.docker.docker_network:
        name: "proxy"
        state: present

    - name: Ensure acme.json has correct permissions for Traefik
      file:
        path: "{{ allVars.path.base.services }}/{{ allVars.dojo.id }}/volumes/config/certificates/acme/acme.json"
        state: touch
        owner: root
        group: root
        mode: 0600
      when: allVars.dojo.tool == 'traefik'

# Creates and set permissions for service-folders
- import_playbook: service-folders.yml
# Creates env file
- import_playbook: env.yml
# Creates all docker-compose files.
- import_playbook: docker-compose.yml
# Ensures folders permissions
- import_playbook: permissions.yml
