---
- name: Create a full folder for the service from the service's dictionary vars
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    hostName: "{{ host }}"
    serviceParam: "{{ service }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./services/base-{{ hostName }}.yml
  tasks:
    # Sets "allVars" array from the service's diccionaries as follows:
    #       baseHost > serviceGeneric > serviceHost > dojoVars.
    - include_tasks: setAllVars.yml

    - name: Ensures "proxy" network exists
      shell:
        cmd: docker network create proxy
      ignore_errors: yes

# Creates and set permissions for service-folders
- import_playbook: service-folders.yml

# Cerates env file
- import_playbook: env.yml

# Creates all docker-compose files.
- import_playbook: docker-compose.yml

# Ensures folders permissions
- import_playbook: permissions.yml
