---
- name: Create docker-compose files from service dictionary vars.
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    hostName: "{{ host }}"
    serviceParam: "{{ service }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./inventory/services/base-{{ hostName }}.yml
  tasks:
    - include_tasks: ../setAllVars.yml
      vars:
        mode: service
        param: "{{ serviceParam }}"

    - name: Generate docker-compose.yml from template
      template:
        src: "./templates/{{ allVars.dojo.tool }}/docker-compose.yml.j2"
        dest: "{{ allVars.path.base.services }}/{{ allVars.dojo.id }}/docker-compose.yml"

    - name: Generate docker-compose.override.yml from template
      template:
        src: "./templates/{{ allVars.dojo.tool }}/docker-compose.override.yml.j2"
        dest: "{{ allVars.path.base.services }}/{{ allVars.dojo.id }}/docker-compose.override.yml"
