---
- name: Set permissions in service folder structure.
  hosts: all
  become: true
  gather_facts: yes
  vars:
    hostName: "{{ host }}"
    serviceParam: "{{ service }}"
    fileCreation: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./configs/dojo.yml
    - ./configs/secret.yml
    - ./inventory/services/base-{{ hostName }}.yml
  tasks:
    - include_tasks: ../setAllVars.yml
      vars:
        mode: service
        param: "{{ serviceParam }}"

    - name: Set ownership on DB folders
      file:
        path: "{{ item }}"
        state: directory
        mode: "0744"
        owner: "999"
        group: "1002"
        recurse: yes
      loop:
        - "{{ allVars.path.volumes.db }}/{{ allVars.dojo.id | lower }}"
        - "{{ allVars.path.volumes.db_import }}/{{ allVars.dojo.id | lower }}"
      tags: volumes_db

    - name: Set ownership on web folders
      file:
        path: "{{ item }}"
        state: directory
        mode: "0744"
        owner: "100"
        group: "101"
        recurse: yes
      loop:
        - "{{ allVars.path.files.config }}/{{ allVars.dojo.id | lower }}"
        - "{{ allVars.path.files.public }}/{{ allVars.dojo.id | lower }}"
        - "{{ allVars.path.files.private }}/{{ allVars.dojo.id | lower }}"
      tags: volumes_www
