---
# INCLUDE - Set global "allVars" array from the service's diccionaries as follows:
#           baseHost > serviceGeneric > serviceHost > dojoVars.

- name: Load vars from dojo.yml
  include_vars:
    file: ./configs/dojo.yml
    name: dojoVars

- name: If exists, load vars from base-host.yml (common to every service in the same host)
  include_vars:
    file: ./inventory/base-{{ hostName }}.yml
    name: baseHostVars
  ignore_errors: yes
  failed_when: false

- name: If exists, load vars from service.yml (same for prod and test)
  include_vars:
    file: ./inventory/{{ serviceParam }}.yml
    name: serviceGenericVars
  ignore_errors: yes
  failed_when: false

- name: If exists, load vars from host/service.yml
  include_vars:
    file: ./inventory/{{ hostName }}/{{ serviceParam }}.yml
    name: serviceHostVars
  ignore_errors: yes
  failed_when: false

- name: Combine/overrides Vars as follows baseHost > serviceGeneric > serviceHost > dojoVars
  set_fact:
    allVars: "{{ dojoVars | combine(baseHostVars | default({}), serviceGenericVars | default({}), serviceHostVars | default({}), recursive=True) }}"


- name: DEBUG - Shows some vars
  debug:
    msg:
      - "GETVARS: ./inventory/{{ hostName }}/{{ serviceParam }}.yml" 
      - "ALLVARS: {{ allVars }}"
      - "SERVICE: {{ serviceHostVars }}"
#       - "SRC: ./templates/{{ allVars.tool }}/apache.ojs.conf-{{ allVars.version }}.j2"
#       - "DEST: {{ allVars.path.files.config }}/{{ allVars.dojo.id }}/apache.conf"


- name: Ensure service's directory exists
  file:
    path: "{{ allVars.path.base.services }}/{{ allVars.dojo.id }}"
    state: directory
    force: yes

