###############################################################################
#
# Function: dojo's Global variables
# Type: Required
#
# Description:
# Global variables for dojo.
# 
# Documentation:
# https://github.com/marcbria/dojo
#
###############################################################################


user:
  run:       "docker"
  group:     "docker"

path:
  base:
    root:    "/home/docker"
    sites:   "/home/docker/sites"
    service: "/home/docker/service"
  storage:  
    root:    "/srv"
    backups: "/srv/backups"
    volumes: "/srv/volumes"
  volumes:
    all:     "/srv/volumes/all"
    db:      "/srv/volumes/db"
    logs:    "/srv/volumes/logs"
  files:
    public:  "/srv/volumes/files/public"
    private: "/srv/volumes/files/private"
    config:  "/srv/volumes/files/config"
