user:
  run:       "docker"
  group:     "docker"
path:
  base:
    root:    "/home/docker"
    sites:   "/home/docker/sites"
    service: "/home/docker/service"
  storage:  
    root:    "/srv"
    backups: "/srv/backups"
    volumes: "/srv/volumes"
  volumes:
    all:     "/srv/volumes/all"
    db:      "/srv/volumes/db"
    files:   "/srv/volumes/files"
    private: "/srv/volumes/files/private"
    public:  "/srv/volumes/files/public"
    config:  "/srv/volumes/files/config"
    logs:    "/srv/volumes/logs"
